/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.main;

import bus.EmployeeBUS;
import bus.impl.EmployeeBUSImpl;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import common.Constants;
import dal.connectDB.ConnectDB;
import gui.FormLoad;
import model.EmployeeEntity;
import gui.menu.Application;
import gui.custom.RoundedButton;
import gui.custom.textfield.PasswordField;
import gui.staff.DialogPasswordRecover;
import gui.staff.MainGUI;
import gui.staff.OverviewGUI;

import java.rmi.RemoteException;
import java.util.List;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.time.format.DateTimeFormatter;
import javax.swing.*;

//import utillity.ReservationCleanupTaskUtil;
import util.ResizeImage;

/**
 *
 * @author ACER
 */
public class LoginGUI extends javax.swing.JFrame {

    public static EmployeeEntity emp;
    private EmployeeBUS empBUS;
    private MainMenu mainMenu;
    private DateTimeFormatter df = DateTimeFormatter.ofPattern("ddMMyy");

    /**
     * Creates new form LonginGUI
     *
     */
    public LoginGUI() throws RemoteException {
        empBUS = FormLoad.employeeBUS;
        initComponents();
        encryptPassword();
        setLocationRelativeTo(null);
        this.txtName.setText(empBUS.getAllEntities().get(0).getEmployeeId());
        this.txtPass.setText("123");

        // Gán phím Enter để kích hoạt sự kiện cho JButton
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = this.getRootPane().getActionMap();

        inputMap.put(KeyStroke.getKeyStroke("ENTER"), "xacNhan");
        actionMap.put("xacNhan", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    btnLoginActionPerformed(null);
                } catch (RemoteException ex) {
                    throw new RuntimeException(ex);
                } catch (Exception ex) {
                    throw new RuntimeException(ex);
                }
            }
        });
    }

    public gui.custom.textfield.TextField getTxtName() {
        return txtName;
    }

    public void setTxtName(String txtName) {
        this.txtName.setText(txtName);
    }

    public PasswordField getTxtPass() {
        return txtPass;
    }

    public void setTxtPass(String txtPass) {
        this.txtPass.setText(txtPass);
    }

    private void encryptPassword() throws RemoteException {
        while (empBUS == null) {
            System.out.println("EmpBus null");
        }

        List<EmployeeEntity> list = empBUS.getAllEntities(); // Thêm dấu ngoặc tròn
        for (EmployeeEntity e : list) {
            if (!isBCryptHash(e.getPassword())) { // Kiểm tra định dạng BCrypt
                e.setPassword(empBUS.hashPassword(e.getPassword())); // Mã hóa mật khẩu
                e = empBUS.updateEntity(e); // Cập nhật vào DB
            }
        }
    }

// Phương thức kiểm tra định dạng BCrypt
    private boolean isBCryptHash(String password) {
        // BCrypt hash thường bắt đầu bằng $2a$, $2b$, hoặc $2y$ và có độ dài chuẩn là 60 ký tự
        return password != null && password.matches("^\\$2[ayb]\\$.{56}$");
    }

    private void resizedImg() {
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/img/restaurant/restaurant.jpg"));
        ImageIcon resizedIcon = ResizeImage.resizeImage(originalIcon, panelLeft.getWidth(), panelLeft.getHeight());
        lblmgRestaurant.setIcon(resizedIcon);

        panelLeft.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                int width = panelLeft.getWidth();
                int height = panelLeft.getHeight();
                ImageIcon resizedIcon = ResizeImage.resizeImage(originalIcon, width, height);
                lblmgRestaurant.setIcon(resizedIcon);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        lblmgRestaurant = new javax.swing.JLabel();
        panelRight = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelLongin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        chkShowId = new javax.swing.JCheckBox();
        btnLogin = new RoundedButton();
        txtName = new gui.custom.textfield.TextField();
        txtPass = new gui.custom.textfield.PasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(939, 544));

        panelLeft.setBackground(new java.awt.Color(102, 0, 0));
        panelLeft.setLayout(new java.awt.BorderLayout());

        lblmgRestaurant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/restaurant/restaurant.jpg"))); // NOI18N
        lblmgRestaurant.setMaximumSize(new java.awt.Dimension(500, 325));
        lblmgRestaurant.setMinimumSize(new java.awt.Dimension(500, 325));
        lblmgRestaurant.setPreferredSize(new java.awt.Dimension(200, 200));
        panelLeft.add(lblmgRestaurant, java.awt.BorderLayout.CENTER);

        panelRight.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/png/logo.png"))); // NOI18N

        panelLongin.setBackground(new java.awt.Color(255, 255, 255));

        lblLogin.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("ĐĂNG NHẬP");
        lblLogin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblLogin.setPreferredSize(new java.awt.Dimension(220, 42));

        chkShowId.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        chkShowId.setForeground(Constants.COLOR_TEXT);
        chkShowId.setText("Hiển thị mật khẩu");
        chkShowId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkShowIdMouseClicked(evt);
            }
        });
        chkShowId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowIdActionPerformed(evt);
            }
        });

        btnLogin.setBackground(Constants.COLOR_PRIMARY);
        btnLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("ĐĂNG NHẬP");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnLoginActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        txtName.setForeground(Constants.COLOR_TEXT);
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setLabelText("Tên đăng nhập");
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtPass.setForeground(Constants.COLOR_TEXT);
        txtPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPass.setLabelText("Mật khẩu");
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    txtPassKeyReleased(evt);
                }  catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout panelLonginLayout = new javax.swing.GroupLayout(panelLongin);
        panelLongin.setLayout(panelLonginLayout);
        panelLonginLayout.setHorizontalGroup(
            panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLonginLayout.createSequentialGroup()
                .addGroup(panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLonginLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkShowId)
                            .addGroup(panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLonginLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        panelLonginLayout.setVerticalGroup(
            panelLonginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLonginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkShowId)
                .addGap(32, 32, 32)
                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLongin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelLongin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quên mật khẩu");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRightLayout.createSequentialGroup()
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnLoginActionPerformed
        String name = txtName.getText().trim();
        String id = new String(txtPass.getPassword());
        if (name.length() == 0) {
            JOptionPane.showMessageDialog(this, "Nhập tên đăng nhập");
            txtName.requestFocus();
            return;
        }
        if (id.length() == 0) {
            JOptionPane.showMessageDialog(this, "Nhập mật khẩu");
            txtPass.requestFocus();
            return;
        }
        emp = empBUS.checkLogin(name, id);
        if (emp != null) {
            FlatRobotoFont.install();
            FlatLaf.registerCustomDefaultsSource("theme");
            UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 20));
            FlatLightLaf.setup();
            if (emp.getRole().getRoleName().equals("STAFF")) {
                Application.app = new Application(1);
                Application.showForm(new MainGUI(Application.app));
                Application.app.setVisible(true);
            } else if (emp.getRole().getRoleName().equals("MANAGER")) {
                Application.app = new Application(2);
                Application.showForm(new OverviewGUI());
                Application.app.setVisible(true);
            }
            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu sai");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked


    }//GEN-LAST:event_btnLoginMouseClicked

    private void chkShowIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkShowIdMouseClicked
        if (chkShowId.isSelected()) {
            txtPass.setEchoChar((char) 0);
        } else {
            txtPass.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowIdMouseClicked

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed

    }//GEN-LAST:event_txtPassActionPerformed

    private void chkShowIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkShowIdActionPerformed

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) throws Exception {//GEN-FIRST:event_txtPassKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLoginActionPerformed(null);
        }
    }//GEN-LAST:event_txtPassKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased

    }//GEN-LAST:event_txtNameKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new DialogPasswordRecover(this).setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        FlatLightLaf.setup();
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ConnectDB.connect();
//                new LoginGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkShowId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblmgRestaurant;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelLongin;
    private javax.swing.JPanel panelRight;
    private gui.custom.textfield.TextField txtName;
    private gui.custom.textfield.PasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
