/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.staff;

import gui.menu.Application;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import util.ReloadComponentUlti;

/**
 *
 * @author Trần Ngọc Huyền.
 */
public class MainGUI extends javax.swing.JPanel {

    /**
     * Creates new form MainGUI
     */
    private OrderGUI orderGUI;
    private TabTable tabTable;
    private TabReservation tabReservation;
    private Application application;

    public MainGUI(Application application) {
        this.application = application;
        orderGUI = new OrderGUI(application, this);
        tabTable = new TabTable(orderGUI);
        tabReservation = new TabReservation(this);
        initComponents();
        addTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();

        setMaximumSize(new java.awt.Dimension(865, 543));
        setMinimumSize(new java.awt.Dimension(865, 543));
        setPreferredSize(new java.awt.Dimension(865, 543));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        panelTop.setLayout(new java.awt.BorderLayout());

        tabMain.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tabMain.setInheritsPopupMenu(true);
        panelTop.add(tabMain, java.awt.BorderLayout.CENTER);

        add(panelTop);
    }// </editor-fold>//GEN-END:initComponents

    public void addTab() {
        tabTable.setLayout(new BoxLayout(tabTable, BoxLayout.Y_AXIS)); // Corrected layout
        tabReservation.setLayout(new BoxLayout(tabReservation, BoxLayout.Y_AXIS)); // Corrected layout
        tabMain.addTab("Sơ đồ bàn", tabTable);
        tabMain.addTab("Đặt bàn", tabReservation);
    }

    public OrderGUI getOrderGUI() {
        return orderGUI;
    }

    public void setOrderGUI(OrderGUI orderGUI) {
        this.orderGUI = orderGUI;
    }

    public TabTable getTabTable() {
        return tabTable;
    }

    public void setTabTable(TabTable tabTable) {
        this.tabTable = tabTable;
    }
   
    public TabReservation getTabReservation() {
        return tabReservation;
    }

    public void setTabReservation(TabReservation tabReservation) {
        this.tabReservation = tabReservation;
    }
    
    public void loadMainGUI() {
        this.getTabTable().loadFloors();
        ReloadComponentUlti.reload(this);
        orderGUI.clearData();
        this.application.showForm(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelTop;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
