/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.staff;

import bus.impl.CategoryBUSImpl;
import bus.impl.ItemBUSImpl;
import common.Constants;
import model.ItemEntity;
import java.util.List;
import gui.FormLoad;
import gui.manager.PromotionGUI;
import gui.manager.ToppingGUI;
import java.awt.Dimension;
import javax.swing.JPanel;
import util.ReloadComponentUlti;

/**
 *
 * @author Trần Ngọc Huyền.
 */
public class PanelCategoryDetail extends javax.swing.JPanel {

    /**
     * Creates new form PanelCategoryDetail
     */
    private CategoryBUSImpl categoryBUSImpl;
    private ItemBUSImpl itemBUSImpl;
    private OrderGUI orderGUI;
    private PromotionGUI promotionGUI;
    private ToppingGUI toppingGUI;

    public PanelCategoryDetail() {
        initComponents();
    }

    public PanelCategoryDetail(List<ItemEntity> items, JPanel parentGUI) {
        this.itemBUSImpl = FormLoad.itemBUSImpl;
        this.categoryBUSImpl = FormLoad.categoryBUSImpl;
        if (parentGUI instanceof OrderGUI) {
            this.orderGUI = (OrderGUI) parentGUI;
        } else if (parentGUI instanceof PromotionGUI) {
            this.promotionGUI = (PromotionGUI) parentGUI;
        } else if (parentGUI instanceof ToppingGUI) {
            this.toppingGUI = (ToppingGUI) parentGUI;
        }
        initComponents();
        loadItemSearch(items);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnItemGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        scrollItems = new javax.swing.JScrollPane();
        panelItems = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 102, 102));
        setMaximumSize(new java.awt.Dimension(112, 102));
        setMinimumSize(new java.awt.Dimension(112, 102));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        scrollItems.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollItems.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollItems.setVerifyInputWhenFocusTarget(false);
        scrollItems.setViewportView(panelItems);

        panelItems.setBackground(Constants.COLOR_BG);
        panelItems.setAutoscrolls(true);
        panelItems.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 20));
        scrollItems.setViewportView(panelItems);

        jPanel1.add(scrollItems);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void loadItemSearch(List<ItemEntity> items) {
        panelItems.removeAll();
        for (ItemEntity item : items) {
            PanelFood pnFood = null;
            if (orderGUI != null) {
                pnFood = new PanelFood(item, orderGUI);
            } else if(promotionGUI != null){
                pnFood = new PanelFood(item, promotionGUI);
            } else if (toppingGUI != null) {
                pnFood = new PanelFood(item, toppingGUI);
            }
            panelItems.add(pnFood);
        }
        int height = items.size() / 4 * 300 + 70;  // 200 là chiều cao mỗi item, bạn có thể điều chỉnh lại theo chiều cao thực tế
        panelItems.setPreferredSize(new Dimension(panelItems.getWidth(), height + 80));
        scrollItems.setViewportView(panelItems);
        ReloadComponentUlti.reload(panelItems);
        ReloadComponentUlti.reload(scrollItems);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnItemGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelItems;
    private javax.swing.JScrollPane scrollItems;
    // End of variables declaration//GEN-END:variables
}
