/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.staff;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.MatteBorder;

/**
 *
 * @author hoang
 */
public class PanelReservationByDate extends javax.swing.JPanel {

    private TabReservation tabReservation;

    /**
     * Creates new form PanelReservationByDate
     */
    public PanelReservationByDate() {
        initComponents();
        this.jPanel2.setBorder(new MatteBorder(0, 3, 0, 0, Color.BLACK));
    }

    public PanelReservationByDate(TabReservation tab) {
        initComponents();
        this.tabReservation = tab;
        this.jPanel2.setBorder(new MatteBorder(0, 3, 0, 0, Color.BLACK));
    }

    public JLabel getLblDate() {
        return lblDate;
    }

    public void setLblDate(String date) {
        this.lblDate.setText(date);
    }

    public JPanel getPanelReservations() {
        return panelReservations;
    }

    public void setPanelReservations(JPanel panelReservations) {
        this.panelReservations = panelReservations;
    }

    public TabReservation getTabReservation() {
        return tabReservation;
    }

    public void setTabReservation(TabReservation tabReservation) {
        this.tabReservation = tabReservation;
    }

    public void removePanelReservation(PanelReservation panelReservation) {
        this.tabReservation.removeFromMapOfAllReservations(panelReservation.getOrder());
        panelReservations.remove(panelReservation);  // Xóa PanelReservation khỏi JPanel
        panelReservations.revalidate();              // Cập nhật lại giao diện
        panelReservations.repaint();                 // Vẽ lại JPanel để hiển thị sự thay đổi
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReservations = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();

        panelReservations.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 25));

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDate.setText("dd-MM-yyyy");
        lblDate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 1392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblDate)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JPanel panelReservations;
    // End of variables declaration//GEN-END:variables
}
