/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.staff;

import bus.impl.OrderBUSImpl;
import common.Constants;
import model.OrderEntity;
import gui.FormLoad;
import gui.custom.RoundedPanel;
import jakarta.persistence.EntityManager;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JLabel;
import model.enums.OrderTypeEnum;

/**
 *
 * @author pc
 */
public class PanelDate extends RoundedPanel {

    private boolean isSelected = false;
    /**
     * Creates new form PanelDate
     */
    private LocalDate date;
    private EntityManager em;
    private OrderBUSImpl orderBUSImpl;
    private TabReservation tabReservation;

    public PanelDate() {
        initComponents();
    }

    public PanelDate(TabReservation tab, LocalDate d) {
        initComponents();

        // Gắn sự kiện vào panelDate
        panelDate.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (!isSelected) {
                    panelDate.setBackground(new Color(220, 220, 220)); // Màu nền khi hover
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                if (!isSelected) {
                    panelDate.setBackground(Color.WHITE); // Màu nền khi không hover
//                    getLblDate().setForeground(Constants.COLOR_TEXT);
//                    getLblnumber().setForeground(Constants.COLOR_TEXT);
                }
            }

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDateMouseClicked(evt); // Gọi sự kiện click
                tabReservation.updatePanelBackground();
                isSelected = true;

                panelDate.setBackground(Constants.COLOR_PRIMARY);
                getLblDate().setForeground(Color.white); // Màu nền khi panel được chọn
                getLblnumber().setForeground(Color.white);
            }
        });

        this.orderBUSImpl = FormLoad.orderBUSImpl;
        this.date = d;
        this.tabReservation = tab;
    }

    public void fillContent() {

        if (lblDate.getText().contains("Hôm nay")) {
            List<OrderEntity> reservations = orderBUSImpl.getListOfReservations(date, LocalTime.now().minusHours(2), OrderTypeEnum.ADVANCE.getOrderType());
            this.tabReservation.setListOfReservationsByOption(reservations);
        } else {
            List<OrderEntity> reservations = orderBUSImpl.getListOfReservations(date, null, OrderTypeEnum.ADVANCE.getOrderType());
            this.tabReservation.setListOfReservationsByOption(reservations);
        }

    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDate = new gui.custom.RoundedPanel();
        lblDate = new javax.swing.JLabel();
        lblnumber = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        panelDate.setBackground(new java.awt.Color(255, 255, 255));
        panelDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDate.setPreferredSize(new java.awt.Dimension(288, 77));
        panelDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDateMouseClicked(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblnumber.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblnumber.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelDateLayout = new javax.swing.GroupLayout(panelDate);
        panelDate.setLayout(panelDateLayout);
        panelDateLayout.setHorizontalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateLayout.createSequentialGroup()
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblnumber)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelDateLayout.setVerticalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDateMouseClicked
        fillContent();
        tabReservation.updatePanelBackground();
        this.panelDate.setBackground(Constants.COLOR_PRIMARY);
    }//GEN-LAST:event_panelDateMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    public JLabel getLblDate() {
        return lblDate;
    }

    public void setLblDate(String lblDate) {
        this.lblDate.setText(lblDate);
    }

    public JLabel getLblnumber() {
        return lblnumber;
    }

    public void setLblnumber(int lblnumber) {
        this.lblnumber.setText(lblnumber + "");
    }

    public RoundedPanel getPanelDate() {
        return panelDate;
    }

    public void setPanelDate(RoundedPanel panelDate) {
        this.panelDate = panelDate;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblnumber;
    private gui.custom.RoundedPanel panelDate;
    // End of variables declaration//GEN-END:variables

    public void deselectPanel() {
        isSelected = false;
        panelDate.setBackground(Color.WHITE); // Trở lại màu ban đầu
    }
}
