/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.menu;

import common.Constants;
import gui.main.LoginGUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Trần Ngọc Huyền
 */
public class PanelClock extends javax.swing.JPanel {

    /**
     * Creates new form PanelClock
     */
    public PanelClock() {
        initComponents();
        startClock();
        String[] temp = LoginGUI.emp.getFullname().trim().split(" ");
        String empName = LoginGUI.emp.getRole().getRoleName().equals("MANAGER") ? "QL - " + temp[temp.length - 1] : "NV - " + temp[temp.length - 1];
        lblEmployee.setText(empName + " - ");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployee = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();

        setBackground(Constants.COLOR_PRIMARY);
        setMinimumSize(new java.awt.Dimension(230, 20));
        setPreferredSize(new java.awt.Dimension(226, 30));
        setLayout(new java.awt.BorderLayout());

        lblEmployee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployee.setText("jLabel1");
        add(lblEmployee, java.awt.BorderLayout.CENTER);

        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 255, 255));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/png/icons8-clock-30.png"))); // NOI18N
        lblClock.setText("jLabel1");
        add(lblClock, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void startClock() {
        // Tạo một Timer để cập nhật giờ mỗi giây (1000 ms)
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateClock();
            }
        });
        timer.start();  // Bắt đầu Timer
    }

    /**
     * Cập nhật đồng hồ lên JLabel (lblClock)
     */
    private void updateClock() {
        // Lấy thời gian hiện tại và định dạng lại (giờ:phút:giây)
        
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        String currentTime = sdf.format(new Date());
        lblClock.setText(currentTime);  // Cập nhật text cho lblClock
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblEmployee;
    // End of variables declaration//GEN-END:variables
}
