/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bus.*;
import bus.impl.*;
import com.formdev.flatlaf.FlatLightLaf;
import common.Constants;
import dal.connectDB.ConnectDB;
import gui.main.LoginGUI;

import java.awt.Color;
import java.rmi.Naming;
import javax.swing.JDialog;

/**
 *
 * @author RAVEN
 */
public class FormLoad extends javax.swing.JDialog {

    /**
     * Creates new form Application
     */
    public static CategoryBUS categoryBUS;
    public static ItemBUS itemBUS;
    public static FloorBUS floorBUS;
    public static TableBUS tableBUS;
    public static CustomerBUS customerBUS;
    public static OrderBUS orderBUS;
    public static OrderDetailBUS orderDetailBUS;
    public static EmployeeBUS employeeBUS;
    public static PromotionBUS promotionBUS;
    public static PromotionDetailBUS promotionDetailBUS;
    public static ToppingBUS toppingBUS;
    public static ItemToppingBUS itemToppingBUS;
    public static RoleBUS roleBUS;

    public FormLoad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(221, 221, 221));
        //  To disable key Alt+F4 to close dialog
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curvesPanel1 = new gui.splashscreen.CurvesPanel();
        jLabel1 = new javax.swing.JLabel();
        pro = new gui.splashscreen.ProgressBarCustom();
        lbStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
//        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        curvesPanel1.setBackground(Constants.COLOR_PRIMARY);
        curvesPanel1.setForeground(new java.awt.Color(153, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/png/logo.png"))); // NOI18N

        lbStatus.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(200, 200, 200));
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus.setText("Status");

        javax.swing.GroupLayout curvesPanel1Layout = new javax.swing.GroupLayout(curvesPanel1);
        curvesPanel1.setLayout(curvesPanel1Layout);
        curvesPanel1Layout.setHorizontalGroup(
                curvesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(curvesPanel1Layout.createSequentialGroup()
                                .addContainerGap(277, Short.MAX_VALUE)
                                .addGroup(curvesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(278, Short.MAX_VALUE))
        );
        curvesPanel1Layout.setVerticalGroup(
                curvesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(curvesPanel1Layout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbStatus)
                                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(curvesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(curvesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    // Load dữ liệu thực tế cho OrderGUI

                    doTask("Loading...", 5);
                    ConnectDB.connect();

                    categoryBUS = (CategoryBUS) Naming.lookup("rmi://localhost:9090/categoryBUS");
                    itemBUS = (ItemBUS) Naming.lookup("rmi://localhost:9090/itemBUS");
                    floorBUS = (FloorBUS) Naming.lookup("rmi://localhost:9090/floorBUS");
                    tableBUS = (TableBUS) Naming.lookup("rmi://localhost:9090/tableBUS");
                    customerBUS = (CustomerBUS) Naming.lookup("rmi://localhost:9090/customerBUS");
                    orderBUS = (OrderBUS) Naming.lookup("rmi://localhost:9090/orderBUS");
                    orderDetailBUS = (OrderDetailBUS) Naming.lookup("rmi://localhost:9090/orderDetailBUS");
                    employeeBUS = (EmployeeBUS) Naming.lookup("rmi://localhost:9090/employeeBUS");
                    promotionBUS = (PromotionBUS) Naming.lookup("rmi://localhost:9090/promotionBUS");
                    toppingBUS = (ToppingBUS) Naming.lookup("rmi://localhost:9090/toppingBUS");
                    itemToppingBUS = (ItemToppingBUS) Naming.lookup("rmi://localhost:9090/itemToppingBUS");
                    promotionDetailBUS = (PromotionDetailBUS) Naming.lookup("rmi://localhost:9090/promotionDetailBUS");
                    roleBUS = (RoleBUS) Naming.lookup("rmi://localhost:9090/roleBUS");

                    doTask("Loading...", 50);

                    doTask("Loading...", 5);
                    // Gọi tầng bus để tải dữ liệu thực tế

                    // Hoàn tất
                    doTask("Done ...", 20);

                    dispose();
                    curvesPanel1.stop();
                    new LoginGUI().setVisible(true);

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }//GEN-LAST:event_formWindowOpened

    private void doTask(String taskName, int progress) throws Exception {
        lbStatus.setText(taskName);
        pro.setValue(progress);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormLoad dialog = new FormLoad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.splashscreen.CurvesPanel curvesPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbStatus;
    private gui.splashscreen.ProgressBarCustom pro;
    // End of variables declaration//GEN-END:variables
}
