/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.manager;

import bus.*;
import dal.connectDB.ConnectDB;
import gui.FormLoad;
import gui.custom.datechooser.DateChooser;
import model.*;
import gui.custom.*;

import java.lang.Exception;
import java.rmi.RemoteException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import util.DatetimeFormatterUtil;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import raven.toast.Notifications;
import util.DoubleFormatUlti;

/**
 *
 * @author ACER
 */
public class SearchGUI extends javax.swing.JPanel {

    private TableDesign tableDesign;
    private EmployeeBUS empBUS;
    private CustomerBUS customerBUS;
    private OrderBUS orderBUS;
    private DefaultTableModel tableModel;
    private TableColumnModel comlumnModel;

    /**
     * Creates new form SearchGUI
     */
    public SearchGUI() throws Exception {
        empBUS = FormLoad.employeeBUS;
        orderBUS = FormLoad.orderBUS;
        customerBUS = FormLoad.customerBUS;
        initComponents();
        loadEmployees();
        loadRank();
        loadTable(LocalDateTime.of(LocalDate.now(), LocalTime.of(00, 00)), LocalDateTime.of(LocalDate.now(), LocalTime.of(23, 59)), "", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void customTable() {
        String[] headers = {"Mã hóa đơn", "Ngày lập", "Nhân viên", "Khách hàng",
            "Tổng tiền", "Xem"};
        List<Integer> tableWidth = Arrays.asList(100, 100, 100, 100, 100, 50);
        tableDesign = new TableDesign(headers, tableWidth);
        table = tableDesign.getTable();
        table.setRowHeight(50);
        tableModel = tableDesign.getModelTable();
        comlumnModel = tableDesign.getColumnModel();
//        table.setColumnModel(comlumnModel);
//        table.setModel(tableModel);
        TableActionEvent actionEvent = new TableActionEvent() {
            @Override
            public void onView(int row) {
                String orderID = table.getValueAt(row, 0).toString();
                OrderEntity o = null;
                try {
                    o = orderBUS.getEntityById(orderID);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                new DialogOrderDetail(o).setVisible(true);
            }

        };
        table.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellViewRender());
        table.getColumnModel().getColumn(5).setCellEditor(new TableActionCellView(actionEvent));
//        tableModel.addRow(new Object[] {"1", "2","3","4", "5" });
    }

    private void loadEmployees() throws Exception {
        cbbStaff.addItem("Chọn nhân viên");
        List<EmployeeEntity> employees = empBUS.getListEmployeeActive();
        for (EmployeeEntity employee : employees) {
            cbbStaff.addItem(employee.getFullname());
        }
    }

    private void loadRank() {
        String[] rank = {"Chọn hạng thành viên", "NEW", "POTENTIAL", "VIP"};
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(rank);
        cbbRank.setModel(model);
    }

    private boolean loadTable(LocalDateTime startDateTime, LocalDateTime endDateTime, String staff, String rank) throws Exception {
        tableModel.setRowCount(0);
        int total = 0;
        double price = 0;
        List<OrderEntity> orders = orderBUS.getListOrder(startDateTime, endDateTime, staff, rank);
        if (orders.isEmpty()) {

            return false;
        }
        for (OrderEntity order : orders) {
            total++;
            price = price + order.getTotalPaid() + order.getDeposit();
            Object[] row = new Object[]{order.getOrderId(), order.getReservationTime(), order.getEmployee().getFullname(),
                order.getCustomer().getLevelCustomer(), DoubleFormatUlti.format(order.getTotalPaid())};

            tableModel.addRow(row);
        }

        lblTotal.setText("Tổng: " + total);
        lblPrice.setText("Doanh Thu: " + DoubleFormatUlti.format(price) + "VND");
        return true;
    }

    private boolean valiData() {
        LocalDate started = LocalDate.parse(txtDateFrist.getText(), DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        LocalDate ended = LocalDate.parse(txtDateEnd.getText(), DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        if (started.isAfter(ended)) {
            Notifications.getInstance().show(
                    Notifications.Type.WARNING,
                    Notifications.Location.TOP_RIGHT,
                    10000,
                    "Thông báo: Vui lòng chọn ngày bắt đầu lớn hơn hoặc bằng ngày kết thúc");
            return false;
        } else {
            LocalDateTime start = started.atStartOfDay(); // 00:00:00
            LocalDateTime end = ended.atTime(23, 59, 59, 999999999); // 23:59:59.999999999
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new gui.custom.datechooser.DateChooser();
        dateChooser2 = new gui.custom.datechooser.DateChooser();
        panelChoice = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        panelDateFirst = new javax.swing.JPanel();
        txtDateFrist = new gui.custom.RoundedTextField();
        lblDateFirst = new javax.swing.JLabel();
        btnDateFirst = new javax.swing.JButton();
        panelStaff = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        cbbStaff = new gui.custom.RoundedComboBox();
        panelRight = new javax.swing.JPanel();
        panelDateEnd = new javax.swing.JPanel();
        txtDateEnd = new gui.custom.RoundedTextField();
        lblDateEnd = new javax.swing.JLabel();
        btnDateEnd = new javax.swing.JButton();
        panelRank = new javax.swing.JPanel();
        lblRank = new javax.swing.JLabel();
        cbbRank = new gui.custom.RoundedComboBox();
        panelFilter = new javax.swing.JPanel();
        btnFilter = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panelTotal = new javax.swing.JPanel();
        lblPrice = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        dateChooser1.setTextRefernce(txtDateFrist);

        dateChooser2.setTextRefernce(txtDateEnd);

        txtDateFrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateFristActionPerformed(evt);
            }
        });

        lblDateFirst.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDateFirst.setText("Ngày bắt đầu:");

        btnDateFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/png/icons8-calendar-40.png"))); // NOI18N
        btnDateFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDateFirstMouseClicked(evt);
            }
        });
        btnDateFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateFirstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDateFirstLayout = new javax.swing.GroupLayout(panelDateFirst);
        panelDateFirst.setLayout(panelDateFirstLayout);
        panelDateFirstLayout.setHorizontalGroup(
            panelDateFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDateFirstLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDateFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(txtDateFrist, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnDateFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        panelDateFirstLayout.setVerticalGroup(
            panelDateFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateFirstLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelDateFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDateFrist, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDateFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblStaff.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStaff.setText("Nhân viên:");

        cbbStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbStaffMouseClicked(evt);
            }
        });
        cbbStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStaffLayout = new javax.swing.GroupLayout(panelStaff);
        panelStaff.setLayout(panelStaffLayout);
        panelStaffLayout.setHorizontalGroup(
            panelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(cbbStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelStaffLayout.setVerticalGroup(
            panelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStaffLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addComponent(panelStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addComponent(panelDateFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addComponent(panelDateFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelChoice.add(panelLeft);

        txtDateEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateEndActionPerformed(evt);
            }
        });

        lblDateEnd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDateEnd.setText("Ngày kết thúc:");

        btnDateEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/png/icons8-calendar-40.png"))); // NOI18N
        btnDateEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDateEndMouseClicked(evt);
            }
        });
        btnDateEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateEndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDateEndLayout = new javax.swing.GroupLayout(panelDateEnd);
        panelDateEnd.setLayout(panelDateEndLayout);
        panelDateEndLayout.setHorizontalGroup(
            panelDateEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDateEndLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDateEndLayout.setVerticalGroup(
            panelDateEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateEndLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelDateEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDateEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDateEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblRank.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRank.setText("Hạng thành viên:");

        cbbRank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbRankMouseClicked(evt);
            }
        });
        cbbRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbRankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRankLayout = new javax.swing.GroupLayout(panelRank);
        panelRank.setLayout(panelRankLayout);
        panelRankLayout.setHorizontalGroup(
            panelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRank, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(cbbRank, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRankLayout.setVerticalGroup(
            panelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRankLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRank, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbRank, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addComponent(panelRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelChoice.add(panelRight);

        btnFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/png/icons8-filter-40.png"))); // NOI18N
        btnFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    btnFilterMouseClicked(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        panelFilter.add(btnFilter);

        panelTable.setLayout(new java.awt.BorderLayout());

        table.setAutoCreateRowSorter(true);
        table.setBackground(new java.awt.Color(245, 245, 245));
        customTable();
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(table);

        panelTable.add(scrollPane, java.awt.BorderLayout.CENTER);

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPrice.setText("Doanh Thu: 0");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotal.setText("Tổng: 0");

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalLayout.createSequentialGroup()
                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTable.add(panelTotal, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(panelChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateFristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateFristActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateFristActionPerformed

    private void txtDateEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateEndActionPerformed

    private void cbbStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbStaffActionPerformed
//        String staff = cbbStaff.getSelectedItem().toString();

    }//GEN-LAST:event_cbbStaffActionPerformed

    private void cbbRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbRankActionPerformed
//        String rank = cbbRank.getSelectedItem().toString();
    }//GEN-LAST:event_cbbRankActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilterActionPerformed

    private void cbbStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbStaffMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbStaffMouseClicked

    private void cbbRankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbRankMouseClicked
        // TODO add your handling code here:ccs
    }//GEN-LAST:event_cbbRankMouseClicked

    private void btnFilterMouseClicked(java.awt.event.MouseEvent evt) throws Exception {//GEN-FIRST:event_btnFilterMouseClicked
        if (valiData()) {
            LocalDate startedDate = LocalDate.parse(txtDateFrist.getText(), DatetimeFormatterUtil.getDateFormatter());
            LocalDateTime startedDateTime = LocalDateTime.of(startedDate, LocalTime.of(0, 0, 1));

            LocalDate endedDate = LocalDate.parse(txtDateEnd.getText(), DatetimeFormatterUtil.getDateFormatter());
            LocalDateTime endedDateTime = LocalDateTime.of(endedDate, LocalTime.of(23, 59, 59));

            String staff = (String) cbbStaff.getSelectedItem();
            String rank = (String) cbbRank.getSelectedItem();

            if (loadTable(startedDateTime, endedDateTime, staff, rank) == false) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả phù hợp!");
                loadTable(LocalDateTime.of(LocalDate.now(), LocalTime.of(00, 00)), LocalDateTime.of(LocalDate.now(), LocalTime.of(23, 59)), "", "");
                return;
            }
            loadTable(startedDateTime, endedDateTime, staff, rank);
        }


    }//GEN-LAST:event_btnFilterMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        String orderDate = tableModel.getValueAt(selectedRow, 1).toString();
        String staff = tableModel.getValueAt(selectedRow, 2).toString();
        String rank = tableModel.getValueAt(selectedRow, 3).toString();

        LocalDateTime dateTime = LocalDateTime.parse(orderDate);
        LocalDate date = dateTime.toLocalDate(); // Chuyển đổi thành LocalDate

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");

        txtDateFrist.setText(date.format(formatter));
        txtDateEnd.setText(date.format(formatter));
        cbbStaff.setSelectedItem(staff);
        cbbRank.setSelectedItem(rank);
    }//GEN-LAST:event_tableMouseClicked

    private void btnDateFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDateFirstActionPerformed

    private void btnDateEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDateEndActionPerformed

    private void btnDateFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDateFirstMouseClicked
        dateChooser1.setVisible(true);
        dateChooser1.requestFocus();
        if (dateChooser1 instanceof DateChooser) {
            ((DateChooser) dateChooser1).showPopup();
        }
    }//GEN-LAST:event_btnDateFirstMouseClicked

    private void btnDateEndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDateEndMouseClicked
        dateChooser2.setVisible(true);
        dateChooser2.requestFocus();
        if (dateChooser2 instanceof DateChooser) {
            ((DateChooser) dateChooser2).showPopup();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDateEndMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDateEnd;
    private javax.swing.JButton btnDateFirst;
    private javax.swing.JButton btnFilter;
    private gui.custom.RoundedComboBox cbbRank;
    private gui.custom.RoundedComboBox cbbStaff;
    private gui.custom.datechooser.DateChooser dateChooser1;
    private gui.custom.datechooser.DateChooser dateChooser2;
    private javax.swing.JLabel lblDateEnd;
    private javax.swing.JLabel lblDateFirst;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRank;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelChoice;
    private javax.swing.JPanel panelDateEnd;
    private javax.swing.JPanel panelDateFirst;
    private javax.swing.JPanel panelFilter;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRank;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelStaff;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    private gui.custom.RoundedTextField txtDateEnd;
    private gui.custom.RoundedTextField txtDateFrist;
    // End of variables declaration//GEN-END:variables
}
